services:
  postgres:
    image: postgres:15
    container_name: bloodstock-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sangue_solidario
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bloodstock-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloodstock-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sangue_solidario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # futuro: integração com user service
      USER_SERVICE_URL: http://user-service:3002

    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  db-data:
